// const name1 = "Ashish";
// const name2 = "Harsha";
// console.log(name1 + " and " + name2 + " are Brothers");
// console.log(`Hello my name is ${name1} and my second name is ${name2}`);
// const gameName = "hitesh-hc";
// console.log(gameName.__proto__);
// console.log(gameName.length);
// console.log(gameName.toUpperCase());
// console.log(gameName.indexOf('g'));
// console.log(gameName.charAt(4));
// console.log(gameName.indexOf('G'));
// console.log(gameName);
// const newString = gameName.slice(-11,4);
// console.log(newString);
const newstring1 = "Ashish";
// console.log(newstring1);
// console.log(newstring1.replace('A', 'B'));
// const newstring2 = newstring1.replace('A','B');
// console.log(newstring2);
// const url = "https://ashish.com/ashish%20kasaudhan";
console.log(url.replace('%20', '-'));
// console.log(newstring1.trim());
console.log(newstring1.includes('Bhish'));